CREATE DATABASE IF NOT EXISTS myDB;

USE myDB;

CREATE TABLE IF NOT EXISTS f1Cars (
    CarID INT AUTO_INCREMENT PRIMARY KEY,
    Team VARCHAR(255) NOT NULL,
    Date TIMESTAMP NOT NULL,
    Location VARCHAR(255) NOT NULL
);
