CREATE DATABASE myDB;
CREATE TABLE NAME( 
person_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NAME	VARCHAR(100) NOT NULL, birthday TIMESTANT NOT NULL DEFAULT CURRENT_TIMESTAMP,
father INT UNSIGNED, 
FOREIGN KEY(father) REFERENCES person(person_id)